--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/luca28pet/AdvancedKits
branches:
- master
projects:
  AdvancedKits:
    path: ""
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: 2.0.0
...
