name: AdvancedKits
main: AdvancedKits\AdvancedKits
version: 7.0.0
api: 5.0.0
author: [luca28pet,skyss0fly]
description: Add kits to your server
website: https://github.com/skyss0fly/AdvancedKits
commands:
  kit:
    description: Get a kit!
    usage: /kit <kitName>
    permission: AdvancedKitsAK.command.kit
  akreload:
    descrpition: Reload Kits settings
    usage: /akreload
    permission: AdvancedKitsAK.command.akreload
  givekit:
    description: Give a kit to someone
    usage: /givekit <kitName> <playerName>
    permission: AdvancedKitsAK.command.givekit
permissions:
  AdvancedKitsAK.command.kit:
    default: true
  AdvancedKitsAK.command.akreload:
    default: op
  AdvancedKitsAK.command.givekit:
    default: op

