name: AdvancedKits
main: AdvancedKits\Main
version: 1.2
api: [1.10.0]

load: POSTWORLD
author: luca28pet
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
commands:
 advancedkits:
  description: Get a kit!
  usage: "/advancedkits <get|vip> [plus]"
  aliases: [ak, kit]
  permission: advancedkits.command
  default: true
permissions:
 advancedkits.command:
  description: "Allows the user to get a kit"
  default: true
