name: AdvancedKits
main: AdvancedKits\Main
version: 1.1
api: [1.3.0]

load: POSTWORLD
author: luca28pet
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
commands:
 advancedkits:
  description: The main command
  usage: "/advancedkits"
  aliases: [ak]
  permission: advancedkits.command
  default: op
permissions:
 advancedkits.command:
  description: "Allows the user to get a kit"
  default: true
