name: AdvancedKits
main: AdvancedKits\Main
version: 3.0
api: [1.12.0]

load: POSTWORLD
author: luca28pet
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
commands:
 kit:
  description: Get a kit!
  usage: "/kit <kitName>"
  aliases: [ak, advancedkits]
  permission: advancedkits.command
permissions:
 advancedkits.command:
  description: "Allows the user to get a kit"
  default: true
 advancedkits.createsign:
  description: "Allows to create kit signs"
  default: op