name: AdvancedKits
main: AdvancedKits\Main
version: 3.0
api: [1.12.0]

load: POSTWORLD
author: luca28pet
description: Add kits to your server
website: https://github.com/luca28pet/AdvancedKits
commands:
 kit:
  description: Get a kit!
  usage: "/kit <kitName>"
  aliases: [ak, advancedkits]
  permission: advancedkits.command
 addkituser:
  description: Let a user get a certain kit
  usage: "/addkituser <kit> <player>"
  permission: advancedkits.admin
 addkitworld:
  description: Let a user get a certain kit in a world
  usage: "/addkitworld <kit> <player>"
  permission: advancedkits.admin
 rmkituser:
  description: Prevent a user to get a certain kit
  usage: "/rmkituser <kit> <player>"
  permission: advancedkits.admin
 rmkitworld:
  description: Prevent a user to get a certain kit in a world
  usage: "/rmkitworld <kit> <player>"
  permission: advancedkits.admin
permissions:
 advancedkits.command:
  description: "Allows the user to get a kit"
  default: true
 advancedkits.admin:
  description: "Allows to manage admin features"
  default: op